name       : sqlheavy
version    : 0.1.1
release    : 2
source     :
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/sqlheavy/sqlheavy-0.1.1.tar.xz : e8689f5fd4e0baf98eada2b3811262bb99877c2e8586fd21ad2a7ad3acc59031
homepage   : https://code.google.com/p/sqlheavy/
license    :
    - LGPL-2.1
    - LGPL-3.0
component  : database
summary    : GObject SQLite wrapper
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(gobject-introspection-1.0)
    - vala
description: |
    GObject SQLite wrapper
setup      : |
    #Borrowed from Arch's pkgbuild
    %patch -p1 < $pkgfiles/sqlheavy-no-utils.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
